on:
  - push
  - pull_request
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - ./
          libraries: |
            - name: LiquidCrystal_I2C
          enable-deltas-report: true